version: '3.4'

services:
  reactsample:
    image: reactsample
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
