# pull official base image
FROM node:lts-alpine as build
ENV NODE_ENV=devlopment
# set working directory
WORKDIR /app
# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
COPY craco.config.js ./
COPY .env ./
RUN npm install -f  

#Copying our project files from our local machine to the working directory in our container.
COPY . ./
RUN npm run test:coverage

# production environment
FROM nginx:stable-alpine
COPY --from=build /app/coverage/lcov-report /usr/share/nginx/html

# new
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
#Setting the default RUN command for our built container to run our test suite.
#CMD ["npm", "run", "test", "--", "--coverage", "--detectOpenHandles"]